#!/bin/bash

# specify bitrate here
export source=$1
export bitrate=$2
export destination=$3

# if your scripts aren't in your $PATH, but are installed, you can specify locations here
export reqs=("ffmpeg" "opusenc")


# don't touch anything below this line ----------------------------


function check {
    printf "Checking %s: " "$1";

    if hash "$1" 2>/dev/null; then # check if command exists
        printf "OK!\n";
    else
        printf "Failed.\n";
        echo "$1 is required to run this script, please install it.";
        exit 1;
    fi
}


function tests {
    for program in "${reqs[@]}"
    do
        check "$program";
    done
}


function help_ {
    echo "Usage: $0 [source] [bitrate] [dest]"
    echo "Example: $0 music 160k transcodes"
}


function convert_opus {
    file=$1
    bitrate=$2
    to_folder=$3

    dest="$to_folder/${file%.flac}.opus"
    directory="$to_folder/${file%/*}"

    mkdir -p "$directory"
    echo "$dest"
    #opusenc --bitrate "$bitrate" "$file" "$dest";
    ffmpeg -i "$file" -acodec libopus -b:a "$bitrate" -vbr on "$dest";
}
export -f convert_opus # exported so I can use it inside find -exec


function main {
    if [ $# -eq 0 ]
    then
        echo "No arguments supplied"
        help_ "$@";
        exit 1;
    fi

    tests;
    find "$source" -name "*.flac" -exec bash -c 'convert_opus "$1" "$bitrate" "$destination"' _ {} \;
}

main "$@"
